Repository thesofproject/sof, pull requests merged in 2019-11, with the labels that each got.

#2023 sof: build: Disallow void pointer arithmetic
  src/arch/host/CMakeLists.txt
  src/arch/host/include/arch/string.h
  src/arch/xtensa/CMakeLists.txt
  src/arch/xtensa/boot_loader.c
  src/arch/xtensa/include/arch/string.h
  src/arch/xtensa/schedule/task.c
  src/audio/buffer.c
  src/audio/dai.c
  src/audio/detect_test.c
  src/audio/kpb.c
  src/audio/pipeline_static.c
  src/audio/src/src_generic.c
  src/audio/src/src_hifi3.c
  src/debug/panic.c
  src/include/sof/audio/buffer.h
  src/include/sof/audio/component.h
  src/include/sof/trace/dma-trace.h
  src/ipc/handler.c
  src/lib/alloc.c
  src/lib/dma.c
  src/platform/intel/cavs/lib/pm_memory.c
  src/platform/intel/cavs/lib/pm_runtime.c
  src/trace/dma-trace.c
  test/cmocka/src/audio/buffer/buffer_write.c
  test/cmocka/src/universal_mocks.c
Labels: Zephyr

#1840 ipc: channel map structures and api
  src/audio/CMakeLists.txt
  src/audio/channel_map.c
  src/include/ipc/channel_map.h
  src/include/sof/audio/channel_map.h
  src/include/sof/common.h
  src/include/user/trace.h
  tools/logger/convert.c
  tools/testbench/trace.c
Labels: ABI

#2115 platform: imx: Update build script for compiling with XCC
  scripts/xtensa-build-all.sh
Labels: IMX

#2116 platform: imx: Enable WAITI_DELAY
  src/platform/Kconfig
Labels: IMX
