Repository thesofproject/sof, pull requests merged in 2020-04, with the labels that each got.

#2522 cc_version: use fixed length for CC_DESC
  src/include/ipc/info.h
  src/include/kernel/abi.h
  src/ipc/cc_version.c
Labels: ABI, P1

#2750 Topology: Add HDA config
  src/include/kernel/tokens.h
  tools/topology/m4/dai.m4
  tools/topology/platform/common/hda.m4
  tools/topology/sof-apl-da7219.m4
  tools/topology/sof-apl-demux-pcm512x.m4
  tools/topology/sof-apl-pcm512x.m4
  tools/topology/sof-apl-rt298.m4
  tools/topology/sof-cml-demux-rt5682.m4
  tools/topology/sof-cml-rt5682-kwd.m4
  tools/topology/sof-cml-rt5682.m4
  tools/topology/sof-cml-rt700.m4
  tools/topology/sof-cml-src-rt5682.m4
  tools/topology/sof-ehl-rt5660.m4
  tools/topology/sof-glk-da7219-kwd.m4
  tools/topology/sof-glk-da7219.m4
  tools/topology/sof-glk-rt5682.m4
  tools/topology/sof-hda-asrc.m4
  tools/topology/sof-hda-generic-idisp.m4
  tools/topology/sof-hda-generic-kwd.m4
  tools/topology/sof-hda-generic.m4
  tools/topology/sof-icl-rt700.m4
  tools/topology/sof-icl-rt711-rt1308-rt715-hdmi.m4
  tools/topology/sof-jsl-da7219.m4
  tools/topology/sof-tgl-max98357a-rt5682.m4
  tools/topology/sof-tgl-max98373-rt5682.m4
  tools/topology/sof-tgl-rt5682.m4
  tools/topology/sof-tgl-rt711-i2s-rt1308.m4
  tools/topology/sof-tgl-rt711-rt1308.m4
  tools/topology/sof/tokens.m4
Labels: ABI

#2673 DMA: Fix fw panic after release on SdW platforms
  src/drivers/dw/dma.c
Labels: P1
