Repository thesofproject/sof, pull requests merged in 2020-09, with the labels that each got.

#2907 dai: atomic trigger operations
  src/audio/dai.c
  src/include/ipc/dai.h
  src/include/sof/lib/dai.h
  src/include/sof/lib/notifier.h
  src/lib/dai.c
Labels: ABI

#3248 smart amp: added Maxim DSM audio component
  src/audio/CMakeLists.txt
  src/audio/Kconfig
  src/audio/smart_amp/CMakeLists.txt
  src/audio/smart_amp/smart_amp.c
  src/audio/smart_amp/smart_amp_generic.c
  src/audio/smart_amp/smart_amp_maxim_dsm.c
  src/include/sof/audio/smart_amp/smart_amp.h
  src/include/user/smart_amp.h
Labels: DSM, Notable, enhancement

#3404 smart_amp: remove hardcoded frame_fmt value
  src/audio/smart_amp_test.c
Labels: P1

#3479 topoplgy: add tgl rt715-rt711-rt1308 support
  tools/topology/CMakeLists.txt
  tools/topology/sof-tgl-rt715-rt711-rt1308-hdmi.m4
Labels: P1
