Repository thesofproject/sof, pull requests merged in 2021-12, with the labels that each got.

#5031 topology: sof-adl-max98360a-rt5682-4ch: add new topology
  tools/topology/topology1/CMakeLists.txt
  tools/topology/topology1/sof-tgl-max98357a-rt5682.m4
Labels: chrome, ADL

#5070 include: add missing tplg tokens to kernel/tokens.h
  src/include/kernel/tokens.h
Labels: ABI

#5081 topology: sof-adl-max98360a-rt5682-4ch: backport to adl-003-drop-stable branch
  tools/topology/CMakeLists.txt
  tools/topology/sof-tgl-max98357a-rt5682.m4
Labels: chrome, ADL

#5129 cmake: fix .ldc chksum fallback when no SOURCE_DIRECTORY/.git
  scripts/cmake/version.cmake
Labels: bug, P1, Zephyr

#5116 topology: sof-adl-max98357a-rt5682-4ch: add new topology
  tools/topology/topology1/CMakeLists.txt
Labels: chrome, ADL

#5117 topology: sof-adl-max98357a-rt5682-4ch: backport to adl-003-drop-stable branch
  tools/topology/CMakeLists.txt
Labels: chrome, ADL
