Repository thesofproject/sof, pull requests merged in 2022-03, with the labels that each got.

#5491 topology1: sof-cml-src-rt5682: remove extra space after values
  tools/topology/topology1/development/sof-cml-src-rt5682.m4
Labels: bug, P1, ADL

#5501 xtensa-build-all.sh: Use appropriate defconfig for tgl-h platform
  scripts/xtensa-build-all.sh
Labels: bug, P1

#5530 xtensa-build-zephyr.sh: add new -u zephyr_remote option
  scripts/xtensa-build-zephyr.sh
Labels: P1

#5528 stable-2.1: xtensa-build-all.sh: Use appropriate defconfig for tgl-h platform
  scripts/xtensa-build-all.sh
Labels: bug, P1

#5570 pipeline: params: don't use uninitialized hw_params
  src/audio/pipeline/pipeline-params.c
Labels: bug, P1
