Repository thesofproject/sof, pull requests merged in 2022-12, with the labels that each got.

#6731 ipc4: copier: remove redundant assignment
  src/audio/copier/copier.c
Labels: static analysis

#6739 west: update rimage and zephyr commits
  west.yml
Labels: static analysis

#6719 ipc4: Fix error handling issues in ipc4
  src/ipc/ipc4/handler.c
Labels: static analysis

#6761 library_manager: fix dma_deinit order
  src/library_manager/lib_manager.c
Labels: static analysis

#6776 buffer: NULL pointer protection
  src/audio/module_adapter/module_adapter.c
Labels: static analysis

#6758 xtensa-build-zephyr.py: objcopy --remove-section .comment zephyr.strip
  scripts/xtensa-build-zephyr.py
Labels: bug, P2

#6788 module adapter: volume: Validation of channels count
  src/audio/module_adapter/module/volume/volume.c
Labels: static analysis

#6846 sof-logger: print error if -u uart option is given with no infile
  tools/logger/logger.c
Labels: P1

#6848 sof-logger: ensure NULL is not passed to printf/fprintf
  tools/logger/convert.c
Labels: P1

#6699 topology: sof-jsl-rt5682: add sof-jsl-rt5682.tplg
  tools/topology/topology1/CMakeLists.txt
  tools/topology/topology1/sof-jsl-rt5682.m4
Labels: topology, JSL, chrome

#6890 [SKIP CI] .github/zephyr: fix uploads overwriting each other
  .github/workflows/zephyr.yml
Labels: bug, P1
