Repository thesofproject/sof, pull requests merged in 2023-03, with the labels that each got.

#7118 topology: sof-jsl-rt5682: backport to jsl-005-drop-stable branch
  tools/topology/CMakeLists.txt
  tools/topology/sof-jsl-rt5682.m4
Labels: topology, JSL, chrome

#7254 xtensa-build-zephyr: fix DEFAULT_TOOLCHAIN_VARIANT spill on next platf
  scripts/xtensa-build-zephyr.py
Labels: bug, P2

#7257 [SKIP CI] zephyr/docker-run.sh: hardcode Linux builds to Zephyr SDK 0.15.2
  .github/workflows/sparse-zephyr.yml
  .github/workflows/zephyr.yml
  zephyr/docker-run.sh
Labels: bug, P1

#7265 smart_amp_test: fix wrong config size in config get
  src/samples/audio/smart_amp_test.c
Labels: static analysis

#7271 ams: handle alloc failures in ams_init()
  src/lib/ams.c
Labels: static analysis

#7273 dai-zephyr: possible division-by-zero if max_block_count is zero
  src/audio/dai-zephyr.c
Labels: static analysis
