Repository thesofproject/sof, pull requests merged in 2023-08, with the labels that each got.

#8003 dp: introduce per-core DP scheduler
  src/include/sof/schedule/dp_schedule.h
  src/init/init.c
  src/schedule/zephyr_dp_schedule.c
Labels: MTL, pipeline2.0, dp_scheduler

#8031 topology1: sof-jsl-rt5650
  tools/topology/CMakeLists.txt
  tools/topology/platform/intel/jsl-rt1015.m4
  tools/topology/sof-jsl-rt5682.m4
Labels: JSL, chrome

#8118 ipc4: helper: adhere to cached/uncached interface
  src/ipc/ipc4/helper.c
Labels: bug, P1
