Repository thesofproject/sof, pull requests merged in 2024-01, with the labels that each got.

#8668 dp: look at all sinks and sources in default "is ready"
  src/include/sof/audio/module_adapter/module/generic.h
Labels: dp_scheduler

#8743 audio: host: reload DMA when partial_size is non zero
  src/audio/host-zephyr.c
Labels: suspend-resume

#8544 library_manager: Update module load flow
  src/include/sof/lib_manager.h
  src/library_manager/Kconfig
  src/library_manager/lib_manager.c
Labels: loadable modules

#8773 topology2: cavs-cs42l43: Add topology for cs42l43/cs35l56 on MTL
  tools/topology/topology2/production/tplg-targets-ace1.cmake
Labels: topology, MTL

#8799 [SKIP SOF-TEST] .github: upgrade all checkout actions, v3 -> v4 (deprecated Node.js 16). Extend fetch-depth when building firmware
  .github/workflows/build_all.yml
  .github/workflows/codestyle.yml
  .github/workflows/installer.yml
  .github/workflows/ipc_fuzzer.yml
  .github/workflows/pull-request.yml
  .github/workflows/repro-build.yml
  .github/workflows/testbench.yml
  .github/workflows/tools.yml
  .github/workflows/unit-tests.yml
  .github/workflows/zephyr.yml
Labels: bug, P1
